---
#------------------------------------------------------------------------------
# Description: Check for existence of pre_update.sh script and run it if
#              found.
#------------------------------------------------------------------------------
- name: Checking if pre_update.sh script exists
  stat:
    path: /opt/home/ansible_svc/pre_update.sh
  register: pre_scripts

- block:
  - name: Running pre_update.sh script
    throttle: 1
    #command: sh /opt/home/ansible_svc/pre_update.sh
    shell: /opt/home/ansible_svc/pre_update.sh > /opt/home/ansible_svc/pre_update.out 2>&1
    when: pre_scripts.stat.exists == true
    ignore_errors: no
  
  - name: Wait for confirmation the app has stopped 
    wait_for: 
      path: /opt/home/ansible_svc/pre_update.out
      search_regex: "stopped"
      #timeout: 300
      timeout: 60 #Maybe set this as a host variable so it can account for each apps/dbs estimated start time. 
      msg: "Application/Database failed to stop in a timely manor, Please investigate!"          
        #notify: (if wait_for failed notify alert handler to raise and alert) 
    when: pre_scripts.stat.exists == true
    ignore_errors: no
